spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github
            clientSecret: github
          google:
            client-id: google
            client-secret: google


