spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: adaa4c74c5e334f9b7ff
            clientSecret: 94ab81ecc4e036e422b43c83c5f8c1b62d44c816
          google:
            client-id: 504272534633-o6mjd7ved92d1a1ejkc6in7k0h4d81t9.apps.googleusercontent.com
            client-secret: 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


